document.writeln("            <hr>");
document.writeln("<p>©2018-2019<a href=\'//xiamuyourenzhang.cn/\' target=\'_blank\'>夏目贵志</a>,Inc.All rights reserved <a href=\'/sitemap.xml\' target=\'_blank\'>sitemap.xml</a>.</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <script src=\'https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js\'></script>");
document.writeln("    <script src=\'https://cdn.bootcss.com/amazeui/2.7.2/js/amazeui.min.js\'></script>");
document.writeln("<script type=\'text/javascript\' src=\'../js\/\/duoshuo.js\'></script>");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'https://hm.baidu.com/hm.js?d2dad54eb9d37bf7966a728848be37ae\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");