document.writeln("    <meta name=\'description\' content=\'夏目贵志のメモ帳,记录友人与你!\' />");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <meta name=\'format-detection\' content=\'telephone=no\'>");
document.writeln("    <meta name=\'renderer\' content=\'webkit\'>");
document.writeln("    <meta http-equiv=\'Cache-Control\' content=\'no-siteapp\' />");
document.writeln("    <link rel=\'alternate icon\' type=\'image/jpg\' href=\'https://avatars1.githubusercontent.com/u/27282832?v=4\'>");
document.writeln("    <link href=\'https://cdn.bootcss.com/amazeui/2.7.2/css/amazeui.min.css\' rel=\'stylesheet\'>");
document.writeln("    <link href=\'https://cdn.bootcss.com/amazeui/2.7.2/css/amazeui.css\' rel=\'stylesheet\'>");
document.writeln("    <style>");
document.writeln("#cd {");
document.writeln("	position: fixed;");
document.writeln("	right: 20px;");
document.writeln("	bottom: 100px;");
document.writeln("}");
document.writeln("");
document.writeln(".header {");
document.writeln("	text-align: center");
document.writeln("}");
document.writeln("");
document.writeln(".header h1 {");
document.writeln("	font-size: 200%;");
document.writeln("	color: #333;");
document.writeln("	margin-top: 30px");
document.writeln("}");
document.writeln("");
document.writeln(".header p {");
document.writeln("	font-size: 14px");
document.writeln("}");
document.writeln("    </style>");